services:
  registry-ssl:
    image: registry:2
    
    restart: always

    ports:
      - "443:443"

    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    
    volumes:
      - $PWD/storage:/var/lib/registry
      - $PWD/auth:/auth
      - $PWD/certs:/certs
