# See vars/main.yaml (top-level) and this role's vars/main.yaml for configuration.

- name: Install Traefik
  when: not (uninstall | bool)
  block:
    - name: Enable Community addons for MicroK8s
      become: true
      ansible.builtin.command: microk8s enable community

    - name: Enable Traefik via MicroK8s
      become: true
      ansible.builtin.command: microk8s enable traefik

- name: Uninstall Traefik
  when: uninstall | bool
  block:
    - name: Disable Traefik via MicroK8s
      become: true
      ansible.builtin.command: microk8s disable traefik
