# See vars/main.yaml (top-level) and this role's vars/main.yaml for configuration.

- name: Render {{ release_name }} values
  become: true
  ansible.builtin.template:
    src: values.yaml.j2
    dest: "/tmp/{{ release_name }}-values-rendered.yaml"
    mode: '0644'
  when: not (uninstall | bool)

- name: Install {{ release_name }}
  ansible.builtin.include_tasks: ../../k8s-base-helm/tasks/install.yaml
  vars:
    chart_version: "{{ traefik_chart_version }}"
    values_file: "/tmp/{{ release_name }}-values-rendered.yaml"
    values_file_remote: true
