# See vars/main.yaml (top-level) and this role's vars/main.yaml for configuration.

- name: Install Podman
  when: not (uninstall | bool)
  block:
    - name: Install Podman
      become: true
      ansible.builtin.apt:
        name: podman
        state: present

- name: Uninstall Podman
  when: uninstall | bool
  block:
    - name: Uninstall Podman
      become: true
      ansible.builtin.apt:
        name: podman
        state: absent
