# See vars/main.yaml (top-level) and this role's vars/main.yaml for configuration.

- name: Check if microk8s snap is installed
  ansible.builtin.command: snap list microk8s
  register: microk8s_check
  failed_when: false
  changed_when: false
  check_mode: false

- name: Install MetalLB
  when: not (uninstall | bool) and microk8s_check.rc == 0 and not (cloud | bool)
  block:
    - name: Fail if "metallb_ip_pool" is undefined
      ansible.builtin.fail: msg="Bailing out. This task requires 'metallb_ip_pool'"
      when: metallb_ip_pool is undefined

    - name: Enable MetalLB
      become: true
      ansible.builtin.command: microk8s enable "metallb:{{metallb_ip_pool}}"

- name: Uninstall MetalLB
  when: uninstall | bool and microk8s_check.rc == 0
  block:
    - name: Disable MetalLB
      become: true
      ansible.builtin.command: microk8s disable metallb
