k8s_core_addons:
  - name: cis-hardening
    controllers: true
    workers: true
  - name: dns
    controllers: true
    workers: true
  - name: hostpath-storage
    controllers: true
    workers: false
  - name: rbac
    controllers: true
    workers: true
