# Structural vars. User-configurable vars are declared in vars/main.yaml (top-level).
helm_release:
  name: headlamp
  namespace: kube-system
  chart:
    ref: headlamp/headlamp
    version: "0.43.0"
  repo:
    name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/
  config: "{{ lookup('ansible.builtin.file', 'values.yaml') | from_yaml }}"
