---
- name: Homelab
  hosts: all
  vars:
    uninstall: false                    # uninstall almost everything
    cloud: false                        # host is running in cloud provider environement
    raspi: false                        # host is running on Raspberry Pi

  roles:
    - role: ../roles/common
      when: not uninstall
    - role: ../roles/k8s-base-microk8s
    - role: ../roles/k8s-extension-metallb
    - role: ../roles/k8s-extension-dashboard
