# Structural vars. User-configurable vars are in vars/main.yaml (top-level).
chart_ref: metallb/metallb
release_name: metallb
release_namespace: metallb-system
repo_name: metallb
repo_url: https://metallb.github.io/metallb
