- name: Run shared preflight checks
  ansible.builtin.include_tasks: ../../../tasks/preflight.yaml

- name: Install {{ k8s_extension_headlamp_trivy_helm_release.name }}
  ansible.builtin.include_tasks: ../../../tasks/helm.yaml
  vars:
    helm_release: "{{ k8s_extension_headlamp_trivy_helm_release }}"
  when: homelab.security.trivy.enabled is true

- name: Install {{ k8s_extension_headlamp_helm_release.name }}
  ansible.builtin.include_tasks: ../../../tasks/helm.yaml
  vars:
    helm_release: "{{ k8s_extension_headlamp_helm_release }}"
