# See vars/main.yaml (top-level) for configuration.

- name: Preflight checks
  ansible.builtin.include_tasks: preflight.yaml
  tags: [preflight]

- name: Setup homelab basics
  ansible.builtin.include_tasks: setup.yaml
  tags: [setup]

- name: Generate summary
  ansible.builtin.include_tasks: summary.yaml
  tags: [summary]
