# See vars/main.yaml (top-level) and this role's vars/main.yaml for configuration.

- name: Setting up homelab basics
  block:
    - name: Ensure homelab directory exists
      ansible.builtin.file:
        path: "{{ homelab_dir | regex_replace('^~', ansible_facts['user_dir']) }}"
        state: directory

    - name: Install basic tools
      become: true
      ansible.builtin.apt:
        pkg:
          - curl
