---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: simple-web
        image: ghcr.io/this-oliver/simple-web-app:v1.0.1@sha256:12f7dfc283ebf48f50284187bb56269b179b605f15a26a92baec8d836d9d0073
        ports:
        - containerPort: 3000
          name: demo-app-http
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: demo-app-http
---
# NOTE: The Gateway API and it's HTTPRoute resource have replaced
# the old school and no-longer-maintained Ingress-NGINX
# controller and IngressRoute resources.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-app
spec:
  parentRefs:
    # the traefik gateway is setup by the homelab automation
    # and situated in the traefik namespace. it handles all
    # HTTP/HTTPS requests that enter the cluster.
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "oliverr.net"
    - "oliverr.localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: demo-app
          port: 80
