---
- name: Bootstrap all nodes
  hosts: all
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Basic
      when: not (uninstall | bool)
      ansible.builtin.include_role:
        name: ../roles/common
