---
- name: Provision certificate management
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Install cert-manager
      ansible.builtin.include_role:
        name: ../roles/k8s-extension-cert-manager
      when: not (uninstall | bool)
      tags: [cert-manager]

    - name: Uninstall cert-manager
      ansible.builtin.include_role:
        name: ../roles/k8s-extension-cert-manager
      when: uninstall | bool
      tags: [cert-manager]
