---
- name: Bootstrap all nodes
  hosts: all
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Basic
      when: not (uninstall | bool)
      ansible.builtin.include_role:
        name: ../roles/common
      tags: [base]

- name: Provision Kubernetes controllers
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Install Kubernetes base
      when: not (uninstall | bool)
      block:
        - name: Kubectl
          ansible.builtin.include_role:
            name: ../roles/k8s-base-kubectl
          tags: [kubectl]

        - name: Helm
          ansible.builtin.include_role:
            name: ../roles/k8s-base-helm
          tags: [helm]

        - name: MicroK8s
          ansible.builtin.include_role:
            name: ../roles/k8s-base-microk8s
          tags: [microk8s]

    - name: Uninstall Kubernetes base
      when: uninstall | bool
      block:
        - name: MicroK8s
          ansible.builtin.include_role:
            name: ../roles/k8s-base-microk8s
          tags: [microk8s]

        - name: Helm
          ansible.builtin.include_role:
            name: ../roles/k8s-base-helm
          tags: [helm]

        - name: Kubectl
          ansible.builtin.include_role:
            name: ../roles/k8s-base-kubectl
          tags: [kubectl]

- name: Provision networking stack
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Install networking stack
      when: not (uninstall | bool)
      block:
        - name: MetalLB
          ansible.builtin.include_role:
            name: ../roles/k8s-extension-metallb
          tags: [metallb]
          when: not (homelab.cloud | bool)

        - name: Gateway API
          ansible.builtin.include_role:
            name: ../roles/k8s-extension-gateway
          tags: [gateway]

        - name: Traefik
          ansible.builtin.include_role:
            name: ../roles/k8s-extension-traefik
          tags: [traefik]

- name: Provision certificate management
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Install cert-manager
      when: not (uninstall | bool)
      ansible.builtin.include_role:
        name: ../roles/k8s-extension-cert-manager
      tags: [cert-manager]

- name: Provision dashboards
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Install Headlamp
      when: not (uninstall | bool)
      ansible.builtin.include_role:
        name: ../roles/k8s-extension-headlamp
      tags: [headlamp]

- name: Generate summary
  hosts: controllers
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: ../tasks/resolve-path.yaml
  tasks:
    - name: Post-install summary
      ansible.builtin.include_role:
        name: ../roles/common
      tags: [summary]
      when: not (uninstall | bool)
