---
- hosts: all
  vars_files:
    - ../vars/main.yaml
  tasks:
    - name: Prepare installation roles
      ansible.builtin.set_fact:
        homelab_roles:
          - ../roles/common
          - ../roles/k8s-base-kubectl
          - ../roles/k8s-base-helm
          - ../roles/k8s-base-microk8s
          - ../roles/k8s-extension-metallb
          - ../roles/k8s-extension-traefik
          - ../roles/k8s-extension-cert-manager
          - ../roles/k8s-extension-headlamp
      when: not (uninstall | bool)

    - name: Prepare uninstall roles
      ansible.builtin.set_fact:
        homelab_roles:
          - ../roles/k8s-extension-metallb
          - ../roles/k8s-base-microk8s
          - ../roles/k8s-base-helm
          - ../roles/k8s-base-kubectl
          - ../roles/common
      when: uninstall | bool

    - name: Execute roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop: "{{ homelab_roles }}"
      loop_control:
        loop_var: role
