---
- name: Provision reverse proxy
  hosts: reverse_proxy
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Resolve homelab directory to an absolute path
      ansible.builtin.include_tasks: _resolve_path.yaml

    - name: Ensure homelab/reverse_proxy directory exists
      ansible.builtin.file:
        path: "{{ homelab.dir }}/reverse-proxy"
        state: directory
        mode: "0755"
  tasks:
    - name: Install Podman
      ansible.builtin.include_role:
        name: ../roles/tool-podman
      when: not (uninstall | bool)
      tags: [podman]

    - name: Uninstall Podman
      ansible.builtin.include_role:
        name: ../roles/tool-podman
      when: uninstall | bool
      tags: [podman]
