---
- hosts: all
  vars:
    uninstall: true                    # uninstall almost everything
    cloud: false                        # host is running in cloud provider environement
    raspi: false                        # host is running on Raspberry Pi
  tasks:
    - when: uninstall is true
      block:
        - name: Uninstall Homelab
          ansible.builtin.include_role:
            name: "{{ item }}"
          loop:
            - ../roles/k8s-extension-cert-manager
            - ../roles/k8s-extension-traefik
            - ../roles/k8s-extension-dashboard
            - ../roles/k8s-extension-metallb
            - ../roles/k8s-base-microk8s
            - ../roles/k8s-base-helm
            - ../roles/k8s-base-kubectl
            - ../roles/common
