- name: Install Traefik
  ansible.builtin.include_tasks:
    file: setup.yaml
  when: not (uninstall | bool)

- name: Uninstall Traefik
  ansible.builtin.include_tasks:
    file: teardown.yaml
  when: uninstall | bool
