name: Continuous Integration
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

jobs:
  check-commit-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          fetch-depth: 0 # fetch all history for commitlint to work

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest

      - name: Install commitlint
        run: |
          npm install commitlint@latest @commitlint/config-conventional

      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose --config .github/config/commitlint.yaml

      - name: Lint PR commits
        if: github.event_name == 'pull_request' && github.event.action != 'edited'
        run: |
            npx commitlint --config .github/config/commitlint.yaml \
              --from ${{ github.event.pull_request.base.sha }} \
              --to ${{ github.event.pull_request.head.sha }} \
              --verbose

  check-ansible-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint ansible files
        run: ansible-lint ansible/
